#!/bin/bash

KEY="500px-with-circle"; CONTENT=\\\\EA01; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="500px"; CONTENT=\\\\EA02; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="add-to-list"; CONTENT=\\\\EA03; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="add-user"; CONTENT=\\\\EA04; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="address"; CONTENT=\\\\EA05; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="adjust"; CONTENT=\\\\EA06; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="air"; CONTENT=\\\\EA07; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="aircraft-landing"; CONTENT=\\\\EA08; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="aircraft-take-off"; CONTENT=\\\\EA09; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="aircraft"; CONTENT=\\\\EA0A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-bottom"; CONTENT=\\\\EA0B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-horizontal-middle"; CONTENT=\\\\EA0C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-left"; CONTENT=\\\\EA0D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-right"; CONTENT=\\\\EA0E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-top"; CONTENT=\\\\EA0F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="align-vertical-middle"; CONTENT=\\\\EA10; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="app-store"; CONTENT=\\\\EA11; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="archive"; CONTENT=\\\\EA12; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="area-graph"; CONTENT=\\\\EA13; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-bold-down"; CONTENT=\\\\EA14; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-bold-left"; CONTENT=\\\\EA15; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-bold-right"; CONTENT=\\\\EA16; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-bold-up"; CONTENT=\\\\EA17; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-down"; CONTENT=\\\\EA18; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-left"; CONTENT=\\\\EA19; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-long-down"; CONTENT=\\\\EA1A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-long-left"; CONTENT=\\\\EA1B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-long-right"; CONTENT=\\\\EA1C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-long-up"; CONTENT=\\\\EA1D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-right"; CONTENT=\\\\EA1E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-up"; CONTENT=\\\\EA1F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-with-circle-down"; CONTENT=\\\\EA20; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-with-circle-left"; CONTENT=\\\\EA21; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-with-circle-right"; CONTENT=\\\\EA22; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="arrow-with-circle-up"; CONTENT=\\\\EA23; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="attachment"; CONTENT=\\\\EA24; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="awareness-ribbon"; CONTENT=\\\\EA25; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="back-in-time"; CONTENT=\\\\EA26; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="back"; CONTENT=\\\\EA27; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="baidu"; CONTENT=\\\\EA28; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bar-graph"; CONTENT=\\\\EA29; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="basecamp"; CONTENT=\\\\EA2A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="battery"; CONTENT=\\\\EA2B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="beamed-note"; CONTENT=\\\\EA2C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="behance"; CONTENT=\\\\EA2D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bell"; CONTENT=\\\\EA2E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="blackboard"; CONTENT=\\\\EA2F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="block"; CONTENT=\\\\EA30; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="book"; CONTENT=\\\\EA31; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bookmark"; CONTENT=\\\\EA32; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bookmarks"; CONTENT=\\\\EA33; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bowl"; CONTENT=\\\\EA34; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="box"; CONTENT=\\\\EA35; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="briefcase"; CONTENT=\\\\EA36; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="browser"; CONTENT=\\\\EA37; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="brush"; CONTENT=\\\\EA38; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bucket"; CONTENT=\\\\EA39; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="bug"; CONTENT=\\\\EA3A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cake"; CONTENT=\\\\EA3B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="calculator"; CONTENT=\\\\EA3C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="calendar"; CONTENT=\\\\EA3D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="camera"; CONTENT=\\\\EA3E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="ccw"; CONTENT=\\\\EA3F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chat"; CONTENT=\\\\EA40; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="check"; CONTENT=\\\\EA41; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-down"; CONTENT=\\\\EA42; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-left"; CONTENT=\\\\EA43; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-right"; CONTENT=\\\\EA44; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-small-down"; CONTENT=\\\\EA45; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-small-left"; CONTENT=\\\\EA46; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-small-right"; CONTENT=\\\\EA47; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-small-up"; CONTENT=\\\\EA48; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-thin-down"; CONTENT=\\\\EA49; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-thin-left"; CONTENT=\\\\EA4A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-thin-right"; CONTENT=\\\\EA4B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-thin-up"; CONTENT=\\\\EA4C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-up"; CONTENT=\\\\EA4D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-with-circle-down"; CONTENT=\\\\EA4E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-with-circle-left"; CONTENT=\\\\EA4F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-with-circle-right"; CONTENT=\\\\EA50; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="chevron-with-circle-up"; CONTENT=\\\\EA51; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="circle-with-cross"; CONTENT=\\\\EA52; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="circle-with-minus"; CONTENT=\\\\EA53; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="circle-with-plus"; CONTENT=\\\\EA54; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="circle"; CONTENT=\\\\EA55; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="circular-graph"; CONTENT=\\\\EA56; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="clapperboard"; CONTENT=\\\\EA57; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="classic-computer"; CONTENT=\\\\EA58; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="clipboard"; CONTENT=\\\\EA59; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="clock"; CONTENT=\\\\EA5A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cloud"; CONTENT=\\\\EA5B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="code"; CONTENT=\\\\EA5C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cog"; CONTENT=\\\\EA5D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="colours"; CONTENT=\\\\EA5E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="compass"; CONTENT=\\\\EA5F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-fast-backward"; CONTENT=\\\\EA60; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-fast-forward"; CONTENT=\\\\EA61; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-jump-to-start"; CONTENT=\\\\EA62; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-next"; CONTENT=\\\\EA63; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-paus"; CONTENT=\\\\EA64; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-play"; CONTENT=\\\\EA65; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-record"; CONTENT=\\\\EA66; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-stop"; CONTENT=\\\\EA67; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="controller-volume"; CONTENT=\\\\EA68; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="copy"; CONTENT=\\\\EA69; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-cloud"; CONTENT=\\\\EA6A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-attribution"; CONTENT=\\\\EA6B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-noderivs"; CONTENT=\\\\EA6C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-noncommercial-eu"; CONTENT=\\\\EA6D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-noncommercial-us"; CONTENT=\\\\EA6E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-public-domain"; CONTENT=\\\\EA6F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-remix"; CONTENT=\\\\EA70; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-share"; CONTENT=\\\\EA71; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons-sharealike"; CONTENT=\\\\EA72; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="creative-commons"; CONTENT=\\\\EA73; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="credit-card"; CONTENT=\\\\EA74; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="credit"; CONTENT=\\\\EA75; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="crop"; CONTENT=\\\\EA76; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cross"; CONTENT=\\\\EA77; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cup"; CONTENT=\\\\EA78; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cw"; CONTENT=\\\\EA79; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="cycle"; CONTENT=\\\\EA7A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="database"; CONTENT=\\\\EA7B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dial-pad"; CONTENT=\\\\EA7C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="direction"; CONTENT=\\\\EA7D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="document-landscape"; CONTENT=\\\\EA7E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="document"; CONTENT=\\\\EA7F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="documents"; CONTENT=\\\\EA80; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dot-single"; CONTENT=\\\\EA81; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dots-three-horizontal"; CONTENT=\\\\EA82; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dots-three-vertical"; CONTENT=\\\\EA83; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dots-two-horizontal"; CONTENT=\\\\EA84; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dots-two-vertical"; CONTENT=\\\\EA85; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="download"; CONTENT=\\\\EA86; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dribbble-with-circle"; CONTENT=\\\\EA87; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dribbble"; CONTENT=\\\\EA88; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="drink"; CONTENT=\\\\EA89; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="drive"; CONTENT=\\\\EA8A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="drop"; CONTENT=\\\\EA8B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="dropbox"; CONTENT=\\\\EA8C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="edit"; CONTENT=\\\\EA8D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="email"; CONTENT=\\\\EA8E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="emoji-flirt"; CONTENT=\\\\EA8F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="emoji-happy"; CONTENT=\\\\EA90; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="emoji-neutral"; CONTENT=\\\\EA91; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="emoji-sad"; CONTENT=\\\\EA92; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="erase"; CONTENT=\\\\EA93; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="eraser"; CONTENT=\\\\EA94; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="evernote"; CONTENT=\\\\EA95; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="export"; CONTENT=\\\\EA96; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="eye-with-line"; CONTENT=\\\\EA97; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="eye"; CONTENT=\\\\EA98; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="facebook-with-circle"; CONTENT=\\\\EA99; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="facebook"; CONTENT=\\\\EA9A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="feather"; CONTENT=\\\\EA9B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="fingerprint"; CONTENT=\\\\EA9C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flag"; CONTENT=\\\\EA9D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flash"; CONTENT=\\\\EA9E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flashlight"; CONTENT=\\\\EA9F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flat-brush"; CONTENT=\\\\EAA0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flattr"; CONTENT=\\\\EAA1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flickr-with-circle"; CONTENT=\\\\EAA2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flickr"; CONTENT=\\\\EAA3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flow-branch"; CONTENT=\\\\EAA4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flow-cascade"; CONTENT=\\\\EAA5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flow-line"; CONTENT=\\\\EAA6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flow-parallel"; CONTENT=\\\\EAA7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flow-tree"; CONTENT=\\\\EAA8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="flower"; CONTENT=\\\\EAA9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="folder-images"; CONTENT=\\\\EAAA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="folder-music"; CONTENT=\\\\EAAB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="folder-video"; CONTENT=\\\\EAAC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="folder"; CONTENT=\\\\EAAD; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="forward"; CONTENT=\\\\EAAE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="foursquare"; CONTENT=\\\\EAAF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="funnel"; CONTENT=\\\\EAB0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="game-controller"; CONTENT=\\\\EAB1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="gauge"; CONTENT=\\\\EAB2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="github-with-circle"; CONTENT=\\\\EAB3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="github"; CONTENT=\\\\EAB4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="globe"; CONTENT=\\\\EAB5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="google-plus-with-circle"; CONTENT=\\\\EAB6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="google-plus"; CONTENT=\\\\EAB7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="google-drive"; CONTENT=\\\\EAB8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="google-hangouts"; CONTENT=\\\\EAB9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="google-play"; CONTENT=\\\\EABA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="graduation-cap"; CONTENT=\\\\EABB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="grid"; CONTENT=\\\\EABC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="grooveshark"; CONTENT=\\\\EABD; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="hair-cross"; CONTENT=\\\\EABE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="hand"; CONTENT=\\\\EABF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="heart-outlined"; CONTENT=\\\\EAC0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="heart"; CONTENT=\\\\EAC1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="help-with-circle"; CONTENT=\\\\EAC2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="help"; CONTENT=\\\\EAC3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="home"; CONTENT=\\\\EAC4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="hour-glass"; CONTENT=\\\\EAC5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="houzz"; CONTENT=\\\\EAC6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="icloud"; CONTENT=\\\\EAC7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="image-inverted"; CONTENT=\\\\EAC8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="image"; CONTENT=\\\\EAC9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="images"; CONTENT=\\\\EACA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="inbox"; CONTENT=\\\\EACB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="infinity"; CONTENT=\\\\EACC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="info-with-circle"; CONTENT=\\\\EACD; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="info"; CONTENT=\\\\EACE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="instagram-with-circle"; CONTENT=\\\\EACF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="instagram"; CONTENT=\\\\EAD0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="install"; CONTENT=\\\\EAD1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="key"; CONTENT=\\\\EAD2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="keyboard"; CONTENT=\\\\EAD3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lab-flask"; CONTENT=\\\\EAD4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="landline"; CONTENT=\\\\EAD5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="language"; CONTENT=\\\\EAD6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="laptop"; CONTENT=\\\\EAD7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lastfm-with-circle"; CONTENT=\\\\EAD8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lastfm"; CONTENT=\\\\EAD9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="layers"; CONTENT=\\\\EADA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="leaf"; CONTENT=\\\\EADB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="level-down"; CONTENT=\\\\EADC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="level-up"; CONTENT=\\\\EADD; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lifebuoy"; CONTENT=\\\\EADE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="light-bulb"; CONTENT=\\\\EADF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="light-down"; CONTENT=\\\\EAE0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="light-up"; CONTENT=\\\\EAE1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="line-graph"; CONTENT=\\\\EAE2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="link"; CONTENT=\\\\EAE3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="linkedin-with-circle"; CONTENT=\\\\EAE4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="linkedin"; CONTENT=\\\\EAE5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="list"; CONTENT=\\\\EAE6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="location-pin"; CONTENT=\\\\EAE7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="location"; CONTENT=\\\\EAE8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lock-open"; CONTENT=\\\\EAE9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="lock"; CONTENT=\\\\EAEA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="log-out"; CONTENT=\\\\EAEB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="login"; CONTENT=\\\\EAEC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="loop"; CONTENT=\\\\EAED; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="magnet"; CONTENT=\\\\EAEE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="magnifying-glass"; CONTENT=\\\\EAEF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mail-with-circle"; CONTENT=\\\\EAF0; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mail"; CONTENT=\\\\EAF1; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="man"; CONTENT=\\\\EAF2; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="map"; CONTENT=\\\\EAF3; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mask"; CONTENT=\\\\EAF4; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="medal"; CONTENT=\\\\EAF5; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="medium-with-circle"; CONTENT=\\\\EAF6; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="medium"; CONTENT=\\\\EAF7; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="megaphone"; CONTENT=\\\\EAF8; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="menu-white"; CONTENT=\\\\EAF9; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="menu"; CONTENT=\\\\EAFA; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="merge"; CONTENT=\\\\EAFB; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="message"; CONTENT=\\\\EAFC; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mic"; CONTENT=\\\\EAFD; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="minus"; CONTENT=\\\\EAFE; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mixi"; CONTENT=\\\\EAFF; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mobile"; CONTENT=\\\\EB00; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="modern-mic"; CONTENT=\\\\EB01; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="moon"; CONTENT=\\\\EB02; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mouse-pointer"; CONTENT=\\\\EB03; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="mouse"; CONTENT=\\\\EB04; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="music"; CONTENT=\\\\EB05; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="network"; CONTENT=\\\\EB06; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="new-message"; CONTENT=\\\\EB07; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="new"; CONTENT=\\\\EB08; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="news"; CONTENT=\\\\EB09; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="newsletter"; CONTENT=\\\\EB0A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="note"; CONTENT=\\\\EB0B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="notification"; CONTENT=\\\\EB0C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="notifications-off"; CONTENT=\\\\EB0D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="old-mobile"; CONTENT=\\\\EB0E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="old-phone"; CONTENT=\\\\EB0F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="onedrive"; CONTENT=\\\\EB10; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="open-book"; CONTENT=\\\\EB11; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="palette"; CONTENT=\\\\EB12; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="paper-plane"; CONTENT=\\\\EB13; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="paypal"; CONTENT=\\\\EB14; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="pencil"; CONTENT=\\\\EB15; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="phone"; CONTENT=\\\\EB16; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="picasa"; CONTENT=\\\\EB17; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="pie-chart"; CONTENT=\\\\EB18; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="pin"; CONTENT=\\\\EB19; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="pinterest-with-circle"; CONTENT=\\\\EB1A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="pinterest"; CONTENT=\\\\EB1B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="plus"; CONTENT=\\\\EB1C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="popup"; CONTENT=\\\\EB1D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="power-plug"; CONTENT=\\\\EB1E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="price-ribbon"; CONTENT=\\\\EB1F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="price-tag"; CONTENT=\\\\EB20; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="print"; CONTENT=\\\\EB21; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="progress-empty"; CONTENT=\\\\EB22; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="progress-full"; CONTENT=\\\\EB23; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="progress-one"; CONTENT=\\\\EB24; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="progress-two"; CONTENT=\\\\EB25; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="publish"; CONTENT=\\\\EB26; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="qq-with-circle"; CONTENT=\\\\EB27; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="qq"; CONTENT=\\\\EB28; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="quote"; CONTENT=\\\\EB29; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="radio"; CONTENT=\\\\EB2A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="raft-with-circle"; CONTENT=\\\\EB2B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="raft"; CONTENT=\\\\EB2C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="rainbow"; CONTENT=\\\\EB2D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="rdio-with-circle"; CONTENT=\\\\EB2E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="rdio"; CONTENT=\\\\EB2F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="remove-user"; CONTENT=\\\\EB30; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="renren"; CONTENT=\\\\EB31; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="reply-all"; CONTENT=\\\\EB32; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="reply"; CONTENT=\\\\EB33; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="resize-100"; CONTENT=\\\\EB34; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="resize-full-screen"; CONTENT=\\\\EB35; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="retweet"; CONTENT=\\\\EB36; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="rocket"; CONTENT=\\\\EB37; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="round-brush"; CONTENT=\\\\EB38; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="rss"; CONTENT=\\\\EB39; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="ruler"; CONTENT=\\\\EB3A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="save"; CONTENT=\\\\EB3B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="scissors"; CONTENT=\\\\EB3C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="scribd"; CONTENT=\\\\EB3D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="select-arrows"; CONTENT=\\\\EB3E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="share-alternative"; CONTENT=\\\\EB3F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="share-alternitive"; CONTENT=\\\\EB40; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="share"; CONTENT=\\\\EB41; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shareable"; CONTENT=\\\\EB42; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shield"; CONTENT=\\\\EB43; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shop"; CONTENT=\\\\EB44; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shopping-bag"; CONTENT=\\\\EB45; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shopping-basket"; CONTENT=\\\\EB46; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shopping-cart"; CONTENT=\\\\EB47; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="shuffle"; CONTENT=\\\\EB48; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="signal"; CONTENT=\\\\EB49; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sina-weibo"; CONTENT=\\\\EB4A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="skype-with-circle"; CONTENT=\\\\EB4B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="skype"; CONTENT=\\\\EB4C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="slideshare"; CONTENT=\\\\EB4D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="smashing"; CONTENT=\\\\EB4E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sound-mix"; CONTENT=\\\\EB4F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sound-mute"; CONTENT=\\\\EB50; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sound"; CONTENT=\\\\EB51; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="soundcloud"; CONTENT=\\\\EB52; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sports-club"; CONTENT=\\\\EB53; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="spotify-with-circle"; CONTENT=\\\\EB54; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="spotify"; CONTENT=\\\\EB55; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="spreadsheet"; CONTENT=\\\\EB56; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="squared-cross"; CONTENT=\\\\EB57; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="squared-minus"; CONTENT=\\\\EB58; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="squared-plus"; CONTENT=\\\\EB59; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="star-outlined"; CONTENT=\\\\EB5A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="star"; CONTENT=\\\\EB5B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="stopwatch"; CONTENT=\\\\EB5C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="stumbleupon-with-circle"; CONTENT=\\\\EB5D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="stumbleupon"; CONTENT=\\\\EB5E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="suitcase"; CONTENT=\\\\EB5F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="swap"; CONTENT=\\\\EB60; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="swarm"; CONTENT=\\\\EB61; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="sweden"; CONTENT=\\\\EB62; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="switch"; CONTENT=\\\\EB63; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tablet-mobile-combo"; CONTENT=\\\\EB64; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tablet"; CONTENT=\\\\EB65; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tag"; CONTENT=\\\\EB66; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="text-document-inverted"; CONTENT=\\\\EB67; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="text-document"; CONTENT=\\\\EB68; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="text"; CONTENT=\\\\EB69; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="thermometer"; CONTENT=\\\\EB6A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="thumbs-down"; CONTENT=\\\\EB6B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="thumbs-up"; CONTENT=\\\\EB6C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="thunder-cloud"; CONTENT=\\\\EB6D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="ticket"; CONTENT=\\\\EB6E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="time-slot"; CONTENT=\\\\EB6F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tools"; CONTENT=\\\\EB70; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="traffic-cone"; CONTENT=\\\\EB71; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="trash"; CONTENT=\\\\EB72; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tree"; CONTENT=\\\\EB73; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="triangle-down"; CONTENT=\\\\EB74; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="triangle-left"; CONTENT=\\\\EB75; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="triangle-right"; CONTENT=\\\\EB76; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="triangle-up"; CONTENT=\\\\EB77; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tripadvisor"; CONTENT=\\\\EB78; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="trophy"; CONTENT=\\\\EB79; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tumblr-with-circle"; CONTENT=\\\\EB7A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tumblr"; CONTENT=\\\\EB7B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="tv"; CONTENT=\\\\EB7C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="twitter-with-circle"; CONTENT=\\\\EB7D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="twitter"; CONTENT=\\\\EB7E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="typing"; CONTENT=\\\\EB7F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="uninstall"; CONTENT=\\\\EB80; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="unread"; CONTENT=\\\\EB81; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="untag"; CONTENT=\\\\EB82; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="upload-to-cloud"; CONTENT=\\\\EB83; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="upload"; CONTENT=\\\\EB84; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="user"; CONTENT=\\\\EB85; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="users"; CONTENT=\\\\EB86; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="v-card"; CONTENT=\\\\EB87; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="video-camera"; CONTENT=\\\\EB88; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="video"; CONTENT=\\\\EB89; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vimeo-with-circle"; CONTENT=\\\\EB8A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vimeo"; CONTENT=\\\\EB8B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vine-with-circle"; CONTENT=\\\\EB8C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vine"; CONTENT=\\\\EB8D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vinyl"; CONTENT=\\\\EB8E; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vk-alternitive"; CONTENT=\\\\EB8F; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vk-with-circle"; CONTENT=\\\\EB90; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="vk"; CONTENT=\\\\EB91; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="voicemail"; CONTENT=\\\\EB92; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="wallet"; CONTENT=\\\\EB93; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="warning"; CONTENT=\\\\EB94; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="water"; CONTENT=\\\\EB95; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="windows-store"; CONTENT=\\\\EB96; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="xing-with-circle"; CONTENT=\\\\EB97; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="xing"; CONTENT=\\\\EB98; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="yelp"; CONTENT=\\\\EB99; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="youko-with-circle"; CONTENT=\\\\EB9A; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="youko"; CONTENT=\\\\EB9B; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="youtube-with-circle"; CONTENT=\\\\EB9C; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
KEY="youtube"; CONTENT=\\\\EB9D; echo -e "\n.entypo.icon {\n  &-$KEY::before {\n    content: \"$CONTENT\";\n  }\n}\n" > $KEY.scss
